#SPDX-License-Identifier: MIT-0
---
# defaults file for postgre_remote
 
postgresql_version: "15"

data_directory: "/etc/postgresql/{{ postgresql_version }}/main"


primary_host: "10.10.10.10"
primary_port: 5432
replication_user: "replicator"
replication_password: "secret"

pg_hba_rules:
  - "host all all 0.0.0.0/0 md5"
  - "host replication replicator 10.0.0.0/24 md5"
