#SPDX-License-Identifier: MIT-0
---
# defaults file for postgre_install
postgresql_version: 15
replication_user: replica
replication_password: secret
replication_network: "10.0.0.0/28"
postgres_admin_user: "Ivan_administrator"
postgres_admin_password: "12345678"
