#SPDX-License-Identifier: MIT-0
---
# defaults file for postgre_restore
backup_file: "/tmp/full_backup.sql.gz"
data_directory: "/var/lib/postgresql/15/main"
postgresql_version: "15"

# Если пользователь хочет пересоздать кластер
force_reinit: false
